DELETE http://localhost:3000/api/v1/users/a000f75b-0a27-4e6e-988b-e93244c1f0d8 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMmYwOTQxNi05ZTY0LTQ1YjctOGJiYS02NjU4MzRjYjVhZjMiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NDYzMTc1MDgsImV4cCI6MTc0NjMxNzgwOH0.cAeCHN-Yo2hSHRPokvUrVREF5pfKn09JmqzTeFlRj20

